openapi: 3.0.1
info:
  title: OpenAI Connector Helper API
  description: This is an API for OpenAI Connector Helper.
  version: 1.0.0
servers:
  - url: http://localhost:7071/api
paths:
  '/convert/{input}/{output}':
    post:
      tags:
        - converter
      operationId: Convert
      parameters:
        - name: input
          in: path
          description: The input file format
          required: true
          schema:
            type: string
        - name: output
          in: path
          description: The output file format
          required: true
          schema:
            type: string
      requestBody:
        description: The input file data
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: The output file data
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        '400':
          description: Either request header or body is invalid
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Resource not found
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Something went wrong
          content:
            text/plain:
              schema:
                type: string
      security:
        - function_key: [ ]
components:
  securitySchemes:
    function_key:
      type: apiKey
      name: x-functions-key
      in: header
