openapi: 3.0.1
info:
  title: OpenAI Connector Helper API
  description: This is an API for OpenAI Connector Helper.
  version: 1.0.0
servers:
  - url: http://localhost:7071/api
paths:
  /convert/audio:
    post:
      tags:
        - converter
      summary: Converts the audio format from one to the other
      description: This operation converts the input audio file format (`webm` by default) to the given output file format (`wav` by default).
      operationId: ConvertAudioFormat
      requestBody:
        description: The input file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/audioFormatRequestModel'
      responses:
        '200':
          description: The output file data
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        '400':
          description: Either request header or body is invalid
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Something went wrong
          content:
            text/plain:
              schema:
                type: string
      security:
        - function_key: [ ]
  '/convert/stt/{locale}':
    post:
      tags:
        - converter
      summary: Converts the voice input to text
      description: This operation converts the voice input to text based on the given locale (`en-au` by default).
      operationId: ConvertSpeechToText
      parameters:
        - name: locale
          in: path
          description: The locale of the voice input
          required: true
          schema:
            type: string
      requestBody:
        description: The input file data
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/speechToTextRequestModel'
      responses:
        '200':
          description: The output file data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speechToTextResponseModel'
        '400':
          description: Either request header or body is invalid
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Something went wrong
          content:
            text/plain:
              schema:
                type: string
      security:
        - function_key: [ ]
components:
  schemas:
    audioFormatRequestModel:
      type: object
      properties:
        input:
          type: string
        output:
          type: string
        inputData:
          type: string
    speechToTextRequestModel:
      type: object
      properties:
        inputData:
          type: string
          format: binary
    speechToTextResponseModel:
      type: object
      properties:
        outputData:
          type: string
  securitySchemes:
    function_key:
      type: apiKey
      name: x-functions-key
      in: header