openapi: 3.0.1
info:
  title: OpenAI Connector Helper API
  description: This is an API for OpenAI Connector Helper.
  version: 1.0.0
servers:
  - url: http://localhost:7071/api
paths:
  /convert/audio:
    post:
      tags:
        - converter
      summary: Audio format conversion
      description: This operation converts the input audio file format (`webm` by default) to `wav`.
      operationId: ConvertAudioFormat
      requestBody:
        description: The input file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/audioFormatRequestModel'
      responses:
        '200':
          description: The output file data
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        '400':
          description: Either request header or body is invalid
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Something went wrong
          content:
            text/plain:
              schema:
                type: string
      security:
        - function_key: [ ]
  '/convert/stt/{locale}':
    post:
      tags:
        - converter
      summary: Audio file to text
      description: This operation converts the audio input to text based on the given locale (`en-au` by default).
      operationId: ConvertSpeechToText
      parameters:
        - name: locale
          in: path
          description: The locale of the audio input
          required: true
          schema:
            type: string
      requestBody:
        description: The input file data
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/audioToTextRequestModel'
      responses:
        '200':
          description: The output file data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/audioToTextResponseModel'
        '400':
          description: Either request header or body is invalid
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Something went wrong
          content:
            text/plain:
              schema:
                type: string
      security:
        - function_key: [ ]
  /convert/voice:
    post:
      tags:
        - converter
      summary: Voice to text
      description: This operation converts the voice input to text based on the given locale (`en-au` by default).
      operationId: ConvertVoiceToTextAsync
      requestBody:
        description: The input file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/voiceToTextRequestModel'
      responses:
        '200':
          description: The output file data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/voiceToTextResponseModel'
        '400':
          description: Either request header or body is invalid
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Something went wrong
          content:
            text/plain:
              schema:
                type: string
      security:
        - function_key: [ ]
components:
  schemas:
    audioFormatRequestModel:
      type: object
      properties:
        input:
          type: string
        inputData:
          type: string
    audioToTextRequestModel:
      type: object
      properties:
        inputData:
          type: string
          format: binary
    audioToTextResponseModel:
      type: object
      properties:
        outputData:
          type: string
    voiceToTextRequestModel:
      type: object
      properties:
        locale:
          type: string
        input:
          type: string
        inputData:
          type: string
    voiceToTextResponseModel:
      type: object
      properties:
        outputData:
          type: string
  securitySchemes:
    function_key:
      type: apiKey
      name: x-functions-key
      in: header